[package]
name = "smart-pot"
version = "0.1.0"
edition = "2021"

[dependencies]
azure_iot_sdk = "0.8.0"
config = "0.15.11"
dotenv = "0.15.0"
env_logger = "0.11.7"
log = "0.4.26"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
