services:
  esp:
    image: espressif/idf-rust:esp32s3_1.85.0.0
    user: root
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    group_add:
      - "${TTY_GROUP_ID}"
    volumes:
      - .:/home/smart-pot
    working_dir: /home/smart-pot
    env_file:
      - .env
    command: cargo run
